### ISSUE TITLE
How to overwrite the version

### ISSUE THREAD

**Issue by mrt181** [jgitver/gradle-jgitver-plugin#11]
Is it possible to overwrite the version?

I would like to append the build-number to the version string on our buildserver prior to deployment.

E.g.:
local build version
`1.0.1-SNAPSHOT`
build server version
`1.0.1-SNAPSHOT+0012`

If not where do I need to look to implement this and create a PR?

**Comment by McFoggy** [comment]
Hi,

I am  really not so used to gradle & groovy but fortunately it is possible.

Given the following simple gradle build

```groovy
plugins {
  id "fr.brouillard.oss.gradle.jgitver" version "0.3.2"
} 

allprojects {
	project.afterEvaluate {
		println "current evaluated project ${project.name}::${project.version}"
		project.version = project.version + '+012-or-whatever-you-want'
		println "updated project ${project.name}::${project.version}"
	}
} 
```

calling jgitver provided task `version` on a fresh newly created project added to git results in:

![image](https://user-images.githubusercontent.com/1119660/40122122-62b16fa2-5923-11e8-919f-35bd9de71783.png)

**Comment by mrt181** [comment]
Hi, yes it works and it's great. This is my current solution to get the build-number from the teamcity build server into the version when building on the build server.

groovy
```
configure(allprojects) {
    project.afterEvaluate {
        if (project.hasProperty("teamcity")) {
            // create a system property 'system.buildCounter = %build.counter%' in teamcity
            project.version = "${project.version}+${project.ext.buildCounter}"
            // set this property in teamcity
            println "##teamcity[buildNumber '${project.version}']"
        }
    }
}
```
you can test is locally like this:
bash
```
$ ./gradlew version -Pteamcity -PbuildCounter=007

> Configure project :
##teamcity[buildNumber '0.6.1-SNAPSHOT+007']

> Task :version
Version: 0.6.1-SNAPSHOT+007

BUILD SUCCESSFUL in 4s
1 actionable task: 1 executed

```

**Comment by McFoggy** [comment]
perfect happy to see that it worked for you and thanks again for sharing your [gradle-jgitver-plugin](https://github.com/jgitver/gradle-jgitver-plugin) usage.

**Comment by soloturn** [comment]
or, if your project is less complex, just read the version in the beginning, and set it:

```
// gradle clean build -PcustomVersion=1.0.0-10-asdf
val customVersion = (project.findProperty("customVersion") ?: "") as String

// some stuff

afterEvaluate {
  if (customVersion != "") {
    project.version = customVersion
  }
}

```
