### ISSUE TITLE
Can nonQualifierBranches be more flexible?

### ISSUE THREAD

**Issue by dmurat** [jgitver/gradle-jgitver-plugin#14]
Is it possible to expand nonQualifierBranches to accept more flexible branch names, something like "feature_*" which will exclude all branches starting with "feature_"?

**Comment by McFoggy** [comment]
honestly I though the configuration was already available in the gradle plugin but it is not.

I created #15 to enhance configuration in the gradle plugin, please follow that issue.
Once it is available you'll be able to do things like in this [junit test from jgitver lib](https://github.com/jgitver/jgitver/blob/master/src/test/java/fr/brouillard/oss/jgitver/strategy/maven/others/Scenario13GitflowWithNonQualifierAndPartialNameTest.java#L85).

Also I created jgitver/jgitver#43 to evaluate another easier solution.

**Comment by McFoggy** [comment]
@dmurat please see #15, I have just uploaded version `0.5.0` that provides you with some configuration possibilities to reach your goal.
