### ISSUE TITLE
allow gradle plugin to specify branching policies

### ISSUE THREAD

**Issue by McFoggy** [jgitver/gradle-jgitver-plugin#15]
[jgitver](https://github.com/jgitver/jgitver) already supports some [BranchingPolicy](https://github.com/jgitver/jgitver/blob/master/src/main/java/fr/brouillard/oss/jgitver/BranchingPolicy.java) that allows for complex configurations of branches handling ; this functionality should be available in gradle  configuration.

**Comment by McFoggy** [comment]
solved with `0.5.0` version.

see [configuration](https://github.com/jgitver/gradle-jgitver-plugin#configuration) paragraph & [examples](https://github.com/jgitver/gradle-jgitver-plugin#configuration-examples) in README.md

each policy requires:
- pattern: a regexp with capturing group
- transformations an array of [BranchNameTransformations](https://github.com/jgitver/jgitver/blob/master/src/main/java/fr/brouillard/oss/jgitver/BranchingPolicy.java#L127) names

**Comment by dmurat** [comment]
Thank you very much. It works great :-)
