### ISSUE TITLE
kotlin DSL build freeze with 0.9.0

### ISSUE THREAD

**Issue by tom-haines** [jgitver/gradle-jgitver-plugin#24]
I am not sure on the root cause, but when changing out kotlin DSL build from 0.8.0 to 0.9.0, gradle (5.4.1) IntelliJ and via CLI freeze with the 0.9.0 version.  I am not sure on the root cause, but could produce a basic example if you don't have an existing kotlin DSL sample/integration type test.

**Comment by McFoggy** [comment]
If you have a small reproducer, it can help thanks.

**Comment by McFoggy** [comment]
related to jgitver/jgitver#86

**Comment by McFoggy** [comment]
can you please try `0.9.1` version

**Comment by tom-haines** [comment]
Will do.  I'm waiting on jgitver-0.11.2 reach [maven central](https://search.maven.org/search?q=a:jgitver), then can re-run against kotlin DSL build.

**Comment by McFoggy** [comment]
thanks.
By the way if it takes too long you can also add temporary sonatype repository to perform the test:
```
    maven {
        url "https://oss.sonatype.org/content/groups/public/"
}
```

**Comment by tom-haines** [comment]
Confirm this issue is fixed by 0.9.1 - thank you.

In IDEA:
- change to 0.9.0 and re-import gradle; Result: stuck in import loop.
- change to 0.9.1 and re-import gradle; Result: no gradle loading issues / fixed.

**Comment by McFoggy** [comment]
may I ask you to provide the layout of your project history by running
```
git log --graph --pretty=format:"%d %h"
```
It will print only the graph with branches/tags/SHA1.

**Comment by tom-haines** [comment]
@McFoggy see [git_log_graph.txt](https://github.com/jgitver/gradle-jgitver-plugin/files/3314677/git_log_graph.txt)

**Comment by McFoggy** [comment]
thank you
