### ISSUE TITLE
Impossible to have version as variable in build.gradle

### ISSUE THREAD

**Issue by sheremeta2018** [jgitver/gradle-jgitver-plugin#25]
Hey, I need to configure another plugin with version calculated by jgitver. It should be something like:
```
plugins {
     id "fr.brouillard.oss.gradle.jgitver" version "0.9.1"
     id 'com.palantir.docker' version '0.22.1'
}

docker {
    name "com.docker.hub/$project.name:$myversion_from_jgitver"
    dockerfile file('Dockerfile')
}
```

Is there some way how to calculate `$myversion_from_jgitver` variable? Thanks

UPD: BTW, it may be very helpful to have a list of all variables of the plugin like Maven version has.

**Comment by McFoggy** [comment]
during **runtime** phase, project.version is correctly set by jgitver.

Also `project.ext.xxx` is set where `xxx` are [Metadatas](https://github.com/jgitver/jgitver/blob/master/src/main/java/fr/brouillard/oss/jgitver/metadata/Metadatas.java#L24) in lower case.

`project.ext.current_version` for example

Your current issue is that, the docker closure here is an extension evaluated by gradle during configuration phase (same as jgitver) and at this point jgitver has not yet been evaluated.

I am not a gradle expert, so I need to investigate more.
If some gradle users read that and can help I would be grateful.

**Comment by McFoggy** [comment]
@sheremeta2018 I over simplified your case

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.palantir.gradle.docker:gradle-docker:0.22.1"
  }
}

class VersionPlugin implements Plugin<Project> {
    void  apply(Project rootProject) {
        def fixedVersion = "1.0"
        rootProject.version = fixedVersion
        rootProject.allprojects { it.version = fixedVersion }
    }
}

apply plugin: VersionPlugin
apply plugin: "com.palantir.docker"

docker {
    name "com.docker.hub/${project.name}:${project.version}"
	buildArgs([PRJ_VERSION: "FromGradle-${project.version}"])
    dockerfile file('Dockerfile')
}
```

and calling `gradle docker` then `docker images` correctly results in expected tag
```
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
com.docker.hub/sample      1.0                 fceee013637c        5 seconds ago       75.3MB
```

I need to understand where the difference comes between jgitver gradle plugin and this over-simplified VersionPlugin.

**Comment by sheremeta2018** [comment]
@McFoggy When I use your plugin in the same manner as described above, I've got `unspecified` as a value for `${project.version}`

- Jar file name is correct: `my-app-0.0.1-1.jar`
- `./gradlew version` returns proper value
- Gradle version: `5.5`

**Comment by McFoggy** [comment]
I know that's why I said:

> I need to understand where the difference comes between jgitver gradle plugin and this over-simplified VersionPlugin.

I welcome any help in this investigation.

**Comment by McFoggy** [comment]
@sheremeta2018 I got it to work now by modifying jgitver to really operate during gradle configuration phase and not after project evaluation.

I'll publish a RC.

**Comment by McFoggy** [comment]
@sheremeta2018 can you try with `0.10.0-rc01` please and confirm it works as expected

![image](https://user-images.githubusercontent.com/1119660/61301657-a094d000-a7e4-11e9-8ecb-b56178d1704e.png)

**Comment by sheremeta2018** [comment]
@McFoggy Yes, it works with ` 0.10.0-rc01`! Thanks a lot!

**Comment by McFoggy** [comment]
I'll leave it as `rc01` for some time waiting for some feedback if any.

**Comment by McFoggy** [comment]
corrected in 98e2e9aa29aa76086820bc4b88ae578591c3b95f with `0.10.0-rc01`

**Comment by anessi** [comment]
I have tested the version 0.10.0-rc01 of the plugin on two or our repositories. It works fine and solves the mentioned problem.

BTW: We worked around the problem before this change by using lazy property evaluation, e.g.
`description = "Pushes the Docker image with tag '${->project.version}' to configured Docker Hub"`

Nice, that this is no longer needed 👍

**Comment by anessi** [comment]
Are you going to release a new version with this fix included in the near future?

**Comment by hjohn** [comment]
The `0.10.0-rc01` does not pick up the `jgitver` config block anymore it seems

**Comment by McFoggy** [comment]
@hjohn you mean that if you provide a config it is not taken into account?

It is strange ; the code is [the same than before](https://github.com/jgitver/gradle-jgitver-plugin/commit/98e2e9aa29aa76086820bc4b88ae578591c3b95f) except that it is executed during configuration phase.
So unless plugin extensions are not available during configuration phase it should work.

Does anyone with gradle knowledge can confirm it should work?

**Comment by McFoggy** [comment]
@hjohn I created #26 

I would appreciate some help from gradle users ; thanks.

**Comment by anessi** [comment]
I just did a quick test and can confirm that the config block is no longer considered. Unfortunately I did not notice this before because I'm not using a config block in the module I used for testing.

**Comment by McFoggy** [comment]
please use `0.10.0-rc02`.

If I have no negative feedback I'll release version `0.10.0`.

see also #26
