### ISSUE TITLE
jgitver configuration closure not used with 0.10.0-rc01

### ISSUE THREAD

**Issue by McFoggy** [jgitver/gradle-jgitver-plugin#26]
with the simple following `build.gradle`

```
plugins {
    id "fr.brouillard.oss.gradle.jgitver" version "0.10.-rc01"
}

jgitver {
    useDirty true
}
```

 the execution `gradle version` on a dirty repository (with single commit) ends in 
```
> Task :version
Version: 0.0.0-0
```

whereas with version `0.9.1` it correctly computes to
```
> Task :version
Version: 0.0.0-0-dirty
```

running jgitver during configuration phase of gradle might have broken the retrieval of extension values.

**Comment by madorb** [comment]
Also running into this issue. No closure configuration seems to be taken into account with `0.10.0-rc1`. `0.9.1` works as expected.

**Comment by McFoggy** [comment]
as already mentionned in #25 I'd need help from gradle users for this to know which way to go is the good one:

* stay like `0.9.1` and use lazy evaluation
* go with `010.0-rc1` refacto and correct config usage
* another way

**Comment by rzabini** [comment]
You might take advantage of the fact that the `setVersion` method in Gradle `Project` class takes an `Object` as parameter, not a `String`. When Gradle needs to output the value of the version, it calls `toString()` on the object. So the _laziness_ is somewhere implicit, if you set the version to a custom object.
So, for instance:
```groovy
class JGitverExtension {
    private final GitVersionCalculator gitVersionCalculator

    JGitverExtension(File rootDir){
        gitVersionCalculator = GitVersionCalculator.location(rootDir)
    }

    void useDirty(boolean useDirty){
        gitVersionCalculator.setUseDirty(useDirty)
    }

    String toString() {
        return gitVersionCalculator.getVersionObject(false).toString()
    }
}
```

```groovy
class JGitverPlugin implements Plugin<Project> {
    void apply(Project project) {
        project.setVersion(project.extensions.create('jgitver',
                JGitverExtension, project.rootDir))
    }
}
```
Now, if you have another plugin

```groovy
class AnotherExtension {
    private String _name

    def name(String name) {
        this._name = name
    }

    String name(){
        _name
    }
}
```

```groovy
class AnotherPlugin implements Plugin<Project> {
    @Override
    void apply(Project project) {
        project.extensions.create('another', AnotherExtension)
    }
}
```
you may use the calculated version, as far as the `jgitver` configuration extension precedes the `another` configuration extension

```groovy
apply plugin: JGitverPlugin
apply plugin: AnotherPlugin

jgitver {
    useDirty true
}

another {
    name "project version is: ${version}"
}

task useJGitver {
    println another.name()
}

```

**Comment by McFoggy** [comment]
Thanks I definitively need to look at that.

**Comment by McFoggy** [comment]
just released `0.10.0-rc02` with lazy evaluation which correct this.

It solves also #25.

@rzabini thanks for your hint

**Comment by anessi** [comment]
I have tested this change and now the configuration closure is considered correctly. The only change I had to do in my build script was changing `project.version` in
```
docker {
  tags project.version, "latest"
  ...
}
```
to either `"{project.version}"` or `project.version.toString()`. The reason is that `tags` only accepts a list of Strings and not Objects. Now the version is no longer a String but a `JGitverLazyVersionHolder` Object, but I guess that's fine.

Thanks for fixing this issue! Happy to use the new version once released. I built it myself for now as the snapshot does not seem to be available on https://plugins.gradle.org/m2/fr/brouillard/oss/gradle/gradle-jgitver-plugin/ (yet?).

**Comment by McFoggy** [comment]
0.10.0-rc03 & 0.10.0-rc02 were pushed to gradle portal : https://plugins.gradle.org/plugin/fr.brouillard.oss.gradle.jgitver

**Comment by anessi** [comment]
I'm seeing 0.10.0-rc03 on https://plugins.gradle.org/plugin/fr.brouillard.oss.gradle.jgitver but don't find the artifact on https://plugins.gradle.org/m2/fr/brouillard/oss/gradle/gradle-jgitver-plugin/

0.10.0-rc02 is also missing there. Maybe something went wrong with publishing the new version?

**Comment by McFoggy** [comment]
afraid that with the changes to kotlin we faced something related to #12

**Comment by anessi** [comment]
Thanks for the hint. After changing
`classpath "fr.brouillard.oss.gradle:gradle-jgitver-plugin:0.10.0-rc03"`
to
`classpath "gradle.plugin.fr.brouillard.oss.gradle:gradle-jgitver-plugin:0.10.0-rc03"`
it works fine and the result is as mentioned in my comment above. So the issue is fixed.
