### ISSUE TITLE
update to jgitver 0.3.0

### ISSUE THREAD

**Issue by McFoggy** [jgitver/gradle-jgitver-plugin#3]
- [ ] update jgitver version
- [ ] expose new configurations possibilities to gradle
- [ ] expose jgitver calculated properties to the build

**Comment by lifuzu** [comment]
Very glad to have this plugin for version!

\+ 1 feature:
prefix version - for some repositories, there are multiple projects inside, could we prefix a project name with the version, such as "myproj-1.0, myproj-1.1" as the lightweight/annotated tag?

Here is the original requirement: http://stackoverflow.com/questions/12796735/git-tag-for-a-subfolder-of-a-repository

**Comment by McFoggy** [comment]
@lifuzu thanks for the positive feedback. 

If you do not mind, I would prefer to have a dedicated issue to be able to discuss your enhancement request. Can you create one in jgitver [issues](https://github.com/jgitver/jgitver/issues) please? Do not hesitate to describe a little bit how you would imagine the versioning resolution could work in such a setup. 

Thanks again, all constructive feedback are always very much appreciated.

**Comment by McFoggy** [comment]
closing this in favor of #5 #6 #7
