### ISSUE TITLE
Current version is not computed correctly in jenkins multi-branch pipeline

### ISSUE THREAD

**Issue by dev-samples** [jgitver/gradle-jgitver-plugin#35]
I am aware this is really not jgitver specific question and rather a CI/Jenkins multi-branch pipeline job question. But maybe someone using jgitver has faced similar issue and can assist and also I found this very nice jgitver wiki:

https://github.com/jgitver/jgitver-maven-plugin/wiki/automatic-builds-for-maven%2C-jenkins-and-gitbucket#jenkins-project-setup

but seems it does not solve the problem I am facing. 

Regarding the issue. Locally I run:

```
$ ./gradlew version
> Task :version
Version: 0.1.2-SNAPSHOT
```
Where:

```
$ git log -2
commit a8... (HEAD -> master, origin/master)
Author: xxx
Date:   xxx

    msg2

commit b7f... (tag: 0.1.1)
Author: xxx
Date:   xxx

    msg1
```
and:

```
jgitver {
  strategy 'MAVEN'
  policy {
     pattern = "(.*)"
     transformations = ['IGNORE']
    }
}
```

So that seems correct.

But when I run the same command from a jenkins multi-branch pipeline job I get:
```
> Task :version
Version: 0.1.2
```
In the checkout stage I have added:
```
stage('Checkout') {
  checkout scm
  sh "git fetch --tags"
}
```

since tags are not cloned by default in multi-branch pipeline job  (even if _Discover tags_ is selected in the job configuration)

Based on:
https://github.com/jgitver/jgitver-maven-plugin/wiki/automatic-builds-for-maven%2C-jenkins-and-gitbucket#jenkins-project-setup

I have also tried to select the _Check out to matching local branch_ and _Filter by name (with wildcards)_ (with **) but that has no effect.

And based on https://github.com/jgitver/gradle-jgitver-plugin#building-on-detached-head setting:

```
stage('Checkout') {
  checkout scm
  sh "git fetch --tags"
  sh "export JGITVER_BRANCH=master"
  sh "./gradlew -Djgitver.branch=master version"
}
```
has no effect either.

Any hints/ideas are much appreciated (again I am aware that this is _really_ not a jgitver issue)!

**Comment by McFoggy** [comment]
You need to use `Advanced clone behaviours` with `fetch tags` checkbox as in the picture below.

![image](https://user-images.githubusercontent.com/1119660/127326850-044e130a-7260-45a9-9018-909b54c8820f.png)

The green rectangle corresponds to the behavior you want : having tags in the workspace ; it is the configuration that `ckeckout scm` command will use.
The orange rectangle corresponds to a MASTER configuration of the pipeline for which Jenkins will fire a build not only on branches discovery but also on tags discovery.

Here is my sample Jenkinsfile
```
pipeline {
    agent {
        node {
            label "docker&&linux"
        }
    }

    triggers  { pollSCM('@yearly')}

    options {
        timestamps() // logs timestamp
        buildDiscarder(logRotator(numToKeepStr: '10')) // nb of builds to keep on master
        disableConcurrentBuilds() // do not allow 2 builds at the same time for a given job
        ansiColor('xterm') // activate coloring in the screen
        disableResume() // restart a "part" of a pipeline after a restart does not work correctly
        timeout(time: 20, unit: 'MINUTES')  // stop if blocked for a long period
    }

    stages {
        stage("Checkout") {
            steps {
                checkout scm
            }
        }

        stage("Git Content") {
            steps {
                sh """
                    git log --oneline -n 10
                    git tag --list
                """
            }
        }
    }
}
```

and the result

![image](https://user-images.githubusercontent.com/1119660/127327341-9d9c7286-c55b-481d-8a8e-88c36ba2b0ca.png)

**Comment by dev-samples** [comment]
I have tried with enabling both those options _Discover tags_ and _Advanced clone behaviors_ with _Fetch tags_  checked but:
  
```
  stage('Checkout') {
     checkout scm

              sh """
                    git log --oneline -n 10
                    git tag --list
                    ./gradlew --stacktrace --info --no-daemon version
               """    
   }
```

Still prints `Version: 0.1.2`:

```
16:06:05  + git log --oneline -n 10
16:06:05  a8cf1e8 update
16:06:05  b7f701f update
16:06:05  98867cc update
16:06:05  7104106 update
16:06:05  e0ca68f update
16:06:05  6700ddf update
16:06:05  8000df0 update
16:06:05  + git tag --list
16:06:05  0.0.2
16:06:05  0.0.3
16:06:05  0.1.0
16:06:05  0.1.1
16:06:05  0.1.2
16:06:05  + ./gradlew --stacktrace --info --no-daemon version
16:06:07  Initialized native services in: /home/jenkins/.gradle/native
...
16:06:19  :version (Thread[Daemon worker,5,main]) started.
16:06:19  
16:06:19  > Task :version
16:06:19  Caching disabled for task ':version' because:
16:06:19    Build cache is disabled
16:06:19  Task ':version' is not up-to-date because:
16:06:19    Task has not declared any outputs despite executing actions.
16:06:19  Version: 0.1.2
16:06:19  :version (Thread[Daemon worker,5,main]) completed. Took 0.061 secs.
```

Instead of expected (when running locally):

```
$ ./gradlew version

> Task :version
Version: 0.1.2-SNAPSHOT
```

I just tried from a "basic" pipelineJob
https://jenkinsci.github.io/job-dsl-plugin/#path/pipelineJob

and there it works fine.  So maybe its something else in the multipipeline job that does not support this?

Also in the sample you provided what happens if you run:

`sh "./gradlew version"`

?

**Comment by dev-samples** [comment]
Seems to be working now. It prints **0.1.3-SNAPSHOT** from jenkins and locally (which is actually the correct value when using maven strategy since last release/annotated tag is 0.1.2):

```
16:36:31  > Task :version
16:36:31  Caching disabled for task ':version' because:
16:36:31    Build cache is disabled
16:36:31  Task ':version' is not up-to-date because:
16:36:31    Task has not declared any outputs despite executing actions.
16:36:31  Version: 0.1.3-SNAPSHOT
16:36:31  :version (Thread[Daemon worker,5,main]) completed. Took 0.058 secs.
```
For reference I am using:

```
    id "fr.brouillard.oss.gradle.jgitver" version "0.9.1"
```
And enabled Fetch tags in multi-branch pipeline using below job dsl/traits:

```
multibranchPipelineJob("sample-job") {
    branchSources {
        branchSource {
            source {
                git {
                    id("sample-job-id") 
                    remote("${gitUrl}")
                    credentialsId("${credentialsI}")
                    traits {
                      gitBranchDiscovery()

                      cloneOptionTrait {
                        extension {
                            noTags( false )
                            shallow( false )
                            reference( '' )
                            timeout( null )                                
                        }
                      }                      
                    }                    
                }
            }
        }
    }
}
```
