### ISSUE TITLE
Does not show expected version - 0.0.0-NOT_A_GIT_REPOSITORY

### ISSUE THREAD

**Issue by mrt181** [jgitver/gradle-jgitver-plugin#4]
Hi,

I have a gradle multi-project

    root
     |--core
     |--ui

I have added the plugin to the ui `build.gradle`
all I get is this:

    >root> ./gradlew version
    :ui:version
    Version: 0.0.0-NOT_A_GIT_REPOSITORY

My git repo contains annotated and lightweight tags. The latest tag is an annotated one,

**Comment by McFoggy** [comment]
can you provide a sample reproducing your problem and the gradle version you use?

**Comment by McFoggy** [comment]
to ease providing the sample, could you please fork & PR on the fresh new [demo-gradle-jgitver-plugin](https://github.com/jgitver/demo-gradle-jgitver-plugin) project. Thanks.

**Comment by McFoggy** [comment]
@mrt181 please review https://github.com/jgitver/demo-gradle-jgitver-plugin/tree/java-projects ; I do not reproduce your problem.

**Comment by mrt181** [comment]
Hi, I retried it from scratch and can't reproduce the problem too - good.
I think that I might have put the jgitver settings in a subproject block previously.

**Comment by McFoggy** [comment]
glad to hear.
